# Generated by Django 5.1.7 on 2025-12-08 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(max_length=15)),
                ('owner_name', models.CharField(max_length=100)),
                ('client_code', models.CharField(max_length=20, null=True, unique=True)),
                ('product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ram_serial', models.CharField(blank=True, max_length=100, null=True)),
                ('ram_manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('ram_part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('disk_model', models.CharField(blank=True, max_length=255, null=True)),
                ('disk_interface_type', models.CharField(blank=True, max_length=100, null=True)),
                ('disk_serial', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
