# Generated by Django 5.2.1 on 2025-06-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(max_length=15)),
                ('owner_name', models.CharField(max_length=100)),
                ('product_id', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=255)),
                ('ram_serial', models.CharField(blank=True, max_length=100, null=True)),
                ('ram_manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('ram_part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('disk_model', models.CharField(blank=True, max_length=255, null=True)),
                ('disk_interface_type', models.CharField(blank=True, max_length=100, null=True)),
                ('disk_serial', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rammodule',
            name='system',
        ),
        migrations.DeleteModel(
            name='Disk',
        ),
        migrations.DeleteModel(
            name='RAMModule',
        ),
        migrations.DeleteModel(
            name='SystemInfo',
        ),
    ]
