# Generated by Django 5.1.7 on 2025-12-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_hardwarerecord_remove_rammodule_system_delete_disk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwarerecord',
            name='client_code',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hardwarerecord',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hardwarerecord',
            name='product_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
