# Generated by Django 5.1.7 on 2025-12-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_hardwarerecord_client_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwarerecord',
            name='client_code',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
