# Generated by Django 5.1.7 on 2025-12-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('owner', 'Owner')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
